name: Error numbers
on:
  pull_request:
    paths:
      - '.github/workflows/errno.yml'
      - 'lib/libc/minimal/include/errno.h'
      - 'scripts/ci/errno.py'

permissions:
  contents: read

jobs:
  check-errno:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.27.4

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Apply container owner mismatch workaround
        run: |
          # FIXME: The owner UID of the GITHUB_WORKSPACE directory may not
          #        match the container user UID because of the way GitHub
          #        Actions runner is implemented. Remove this workaround when
          #        GitHub comes up with a fundamental fix for this problem.
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Environment Setup
        run: |
          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-$( cat SDK_VERSION )" >> $GITHUB_ENV

      - name: Run errno.py
        run: |
          export ZEPHYR_BASE=${PWD}
          ./scripts/ci/errno.py
